name: build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}
  repository_dispatch: {}

jobs:
  build:
    if: github.repository == 'mmistakes/minimal-mistakes'
    runs-on: ubuntu-latest
    steps:
    - name: Chectout code
      uses: actions/checkout@v2
    - name: Download and install ruby-build
        run: |
          # 下载 ruby-build 的 tarball
          curl -LO https://github.com/rbenv/ruby-build/releases/latest/download/ruby-build.tar.gz
          
          # 解压文件
          tar -xzf ruby-build.tar.gz
          
          # 安装 ruby-build
          PREFIX=/opt/hostedtoolcache ./ruby-build-*/install.sh
          
          # 删除 tarball 和解压目录，节省空间
          rm -rf ruby-build-*
          rm ruby-build.tar.gz

    - name: Install Ruby
        run: |
          /opt/hostedtoolcache/bin/ruby-build 3.1.2 /opt/hostedtoolcache/Ruby/3.1.2/x64
          touch /opt/hostedtoolcache/Ruby/3.1.2/x64.complete
        shell: bash

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    - name: Setup cache for Bundler
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          docs/Gemfile.lock
          docs/vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('docs/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    - name: Install - Bundler
      env:
        MAKE: make -j2
      working-directory: docs/
      run: |
        bundle config set path vendor/bundle
        bundle install --jobs=4 --retry=3
        bundle clean

    - name: Update Algolia index
      working-directory: docs/
      run: bundle exec jekyll algolia push
      env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      continue-on-error: true
