name: build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}
  repository_dispatch: {}

jobs:
  build:
    if: github.repository == 'mmistakes/minimal-mistakes'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 手动安装Ruby
    - name: Setup Ruby manually
      run: |
        sudo apt-get update
        sudo apt-get install -y rbenv ruby-build
        sudo mkdir -p /opt/hostedtoolcache/Ruby/3.2.3/x64
        sudo ruby-build 3.2.3 /opt/hostedtoolcache/Ruby/3.2.3/x64
        sudo touch /opt/hostedtoolcache/Ruby/3.2.3/x64.complete
        echo "PATH=/opt/hostedtoolcache/Ruby/3.2.3/x64/bin:$PATH" >> $GITHUB_ENV
        gem install bundler
    
    - name: Setup cache for Bundler
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          docs/Gemfile.lock
          docs/vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('docs/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    - name: Install - Bundler
      env:
        MAKE: make -j2
      working-directory: docs/
      run: |
        bundle config set path vendor/bundle
        bundle install --jobs=4 --retry=3
        bundle clean

    - name: Update Algolia index
      working-directory: docs/
      run: bundle exec jekyll algolia push
      env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      continue-on-error: true
